1 : A thin 23 cm pizza base.
2 : 2 tbs salt-reducedtomato paste.
3 : 1 cup (30g) baby spinach leaves.
4 : half large red onion, peeled, finely sliced and separated.
5 : 100g cooked or BBQ chicken breast, thinly sliced.
6 : half small red capsicum, seeded and sliced into thin strips.
7 : 6 large cherry tomatoes, halved.
8 : half cup grated reduced-fat mozzarella cheese.
9 : Basil leaves, to serve.
